# Generated by Django 5.1.1 on 2024-10-25 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wheretoplayApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VotingStatus',
            fields=[
                ('voting_status_id', models.AutoField(primary_key=True, serialize=False)),
                ('voting_status', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'voting_status',
                'managed': True,
            },
        ),
        migrations.RenameField(
            model_name='vote',
            old_name='items_id',
            new_name='criteria_id',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='user_category_id',
        ),
        migrations.RemoveField(
            model_name='sessionparticipant',
            name='user_category_id',
        ),
        migrations.RemoveField(
            model_name='votingsession',
            name='user_id',
        ),
        migrations.AddField(
            model_name='usercategory',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sessionparticipant',
            name='guest_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wheretoplayApp.guest'),
        ),
        migrations.AlterField(
            model_name='sessionparticipant',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vote',
            name='guest_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wheretoplayApp.guest'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='votingsession',
            name='voting_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wheretoplayApp.votingstatus'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('workspace_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'workspace',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='opportunity',
            name='workspace_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wheretoplayApp.workspace'),
            preserve_default=False,
        ),
    ]
