# Generated by Django 5.1.1 on 2024-10-28 03:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wheretoplayApp', '0002_votingstatus_rename_items_id_vote_criteria_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opportunity',
            old_name='opp_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='opportunitystatus',
            old_name='opp_status_id',
            new_name='status_id',
        ),
        migrations.RenameField(
            model_name='sessionparticipant',
            old_name='guest_id',
            new_name='guest',
        ),
        migrations.RenameField(
            model_name='sessionparticipant',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='sessionparticipant',
            old_name='vs_id',
            new_name='voting_session',
        ),
        migrations.RenameField(
            model_name='usercategory',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='vote',
            old_name='criteria_id',
            new_name='criteria',
        ),
        migrations.RenameField(
            model_name='vote',
            old_name='guest_id',
            new_name='guest',
        ),
        migrations.RenameField(
            model_name='vote',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='vote',
            old_name='vs_id',
            new_name='voting_session',
        ),
        migrations.RenameField(
            model_name='workspace',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='opp_category_id',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='opp_status_id',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='workspace_id',
        ),
        migrations.RemoveField(
            model_name='votingsession',
            name='opportunity_id',
        ),
        migrations.AddField(
            model_name='opportunity',
            name='opp_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wheretoplayApp.opportunitycategory'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wheretoplayApp.opportunitystatus'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wheretoplayApp.workspace'),
        ),
        migrations.AddField(
            model_name='votingsession',
            name='opportunity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wheretoplayApp.opportunity'),
        ),
        migrations.AlterField(
            model_name='opportunitystatus',
            name='label',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='votecriteria',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='votingsession',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='votingsession',
            name='url_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='votingsession',
            name='voting_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wheretoplayApp.votingstatus'),
        ),
    ]
