# Generated by Django 5.1.1 on 2024-10-29 00:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wheretoplayApp', '0003_rename_opp_name_opportunity_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
