# Generated by Django 5.1.1 on 2024-10-29 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wheretoplayApp', '0004_alter_workspace_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opportunity',
            name='opp_category',
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='votingsession',
            name='code',
        ),
        migrations.RemoveField(
            model_name='votingsession',
            name='url_link',
        ),
        migrations.AddField(
            model_name='workspace',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='url_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='OpportunityCategory',
        ),
        migrations.DeleteModel(
            name='OpportunityStatus',
        ),
    ]
