# Generated by Django 5.1.1 on 2024-11-03 19:45

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wheretoplayApp', '0006_votesfor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='criteria',
        ),
        migrations.RemoveField(
            model_name='votesfor',
            name='user',
        ),
        migrations.RemoveField(
            model_name='votesfor',
            name='workspace',
        ),
        migrations.RenameField(
            model_name='votingsession',
            old_name='vs_id',
            new_name='session_id',
        ),
        migrations.RemoveField(
            model_name='sessionparticipant',
            name='guest',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='guest',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='voting_session',
        ),
        migrations.RemoveField(
            model_name='votingsession',
            name='opportunity',
        ),
        migrations.AddField(
            model_name='vote',
            name='criteria_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vote',
            name='opportunity',
            field=models.ForeignKey(default=999, on_delete=django.db.models.deletion.CASCADE, to='wheretoplayApp.opportunity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='votingsession',
            name='code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voting_sessions', to='wheretoplayApp.workspace'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wheretoplayApp.workspace'),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='code',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.DeleteModel(
            name='VoteCriteria',
        ),
        migrations.DeleteModel(
            name='VotesFor',
        ),
    ]
