# Generated by Django 5.1.1 on 2024-11-03 19:57

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wheretoplayApp', '0007_remove_vote_criteria_remove_votesfor_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Image'),
        ),
    ]
