# Generated by Django 5.1.1 on 2024-11-06 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wheretoplayApp', '0008_alter_opportunity_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='url_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
