# Generated by Django 5.1.1 on 2024-11-16 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wheretoplayApp', '0011_passwordreset'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passwordreset',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='passwordreset',
            table='password_reset',
        ),
    ]
