# Generated by Django 5.1.1 on 2024-11-19 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wheretoplayApp', '0012_alter_passwordreset_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='outlier_threshold',
            field=models.FloatField(default=2),
        ),
    ]
